{"_default": {"1": {"GoogleCodeExporter": {"issues": [{"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/23", "title": "Pidfile handling improvements", "body": "```\nI've attached three patches which improve mainly the pidfile handling and \nWindows compatibility.\n\n01_pidfile_setting.patch - Adds a settings variable for the pidfile (similarly \nto the one for the logfile). This enables running multiple instances of taskd \non the same machine.\n\n02_logfile_tmp_path.patch - Adds the same logic for determining the temp path \nfor the logfile as the pidfile uses.\n\n03_remove_stale_pidfile.patch - Removes the stale pidfile on startup. Also adds \nbetter support for checking whether a process exists with a given pid. This \nworks on Windows too, although it requires psutil (but only on Windows).\n```\n\nOriginal issue reported on code.google.com by `akos.lad...@gmail.com` on 20 Nov 2014 at 9:48\n\nAttachments:\n- [01_pidfile_setting.patch](https://storage.googleapis.com/google-code-attachments/django-tasks/issue-23/comment-0/01_pidfile_setting.patch)\n- [02_logfile_tmp_path.patch](https://storage.googleapis.com/google-code-attachments/django-tasks/issue-23/comment-0/02_logfile_tmp_path.patch)\n- [03_remove_stale_pidfile.patch](https://storage.googleapis.com/google-code-attachments/django-tasks/issue-23/comment-0/03_remove_stale_pidfile.patch)\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/23/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/22", "title": "pip installation forces Django 1.5 even if more recent version is installed", "body": "```\nWhat steps will reproduce the problem?\n1. Install Django > 1.5\n2. run pip install django-tasks\n\nWhat is the expected output? What do you see instead?\nI expect the installation to notice that I have Django 1.5.5 installed and \nproceed without downgrading the existing installation. Instead pip removes \nDjango 1.5.5 and installs 1.5 instead\n\nWhat version of the product are you using? On what operating system?\ndjango-tasks-0.3 installation with \"pip 1.5.2 from \n/usr/lib/python2.6/site-packages/pip-1.5.2-py2.6.egg (python 2.6)\" on Amazon \nLinux\n\nPlease provide any additional information below.\nCopy of installation output\n[ec2-user]$ sudo pip install django-tasks\nDownloading/unpacking django-tasks\n  Downloading django-tasks-0.3.tar.gz\n  Running setup.py (path:/tmp/pip_build_root/django-tasks/setup.py) egg_info for package django-tasks\nDownloading/unpacking django==1.5 (from django-tasks)\n  Downloading Django-1.5.tar.gz (8.0MB): 8.0MB downloaded\n  Running setup.py (path:/tmp/pip_build_root/django/setup.py) egg_info for package django\n    warning: no previously-included files matching '__pycache__' found under directory '*'\n    warning: no previously-included files matching '*.py[co]' found under directory '*'\nRequirement already satisfied (use --upgrade to upgrade): south in \n/usr/lib64/python2.6/site-packages (from django-tasks)\nInstalling collected packages: django-tasks, django\n  Running setup.py install for django-tasks\n  Found existing installation: Django 1.5.5\n    Uninstalling Django:\n      Successfully uninstalled Django\n  Running setup.py install for django\n    changing mode of build/scripts-2.6/django-admin.py from 644 to 755\n    warning: no previously-included files matching '__pycache__' found under directory '*'\n    warning: no previously-included files matching '*.py[co]' found under directory '*'\n    changing mode of /usr/bin/django-admin.py to 755\nSuccessfully installed django-tasks django\nCleaning up...\n\n```\n\nOriginal issue reported on code.google.com by `jukka.ho...@gmail.com` on 28 Jan 2014 at 12:46\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/22/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/21", "title": "If tasks take longer than 5 seconds, multiple tasks get started", "body": "```\nWhat steps will reproduce the problem?\n\n1. Start multiple tasks longer that take longer than 5 seconds \n\nWhat is the expected output? What do you see instead?\n\nOnly one tasks should start, and the remainding tasks should wait for it to \nfinish. However, every 5 seconds, a new task is started regardless of how many \ntasks are already running.\n\nWhat version of the product are you using? On what operating system?\n\nr51, using Django 1.6 on Ubuntu 12.04 Server.\n\nPlease provide any additional information below.\n\nI've attached a patch that checks for running tasks and only starts a new task \nif there aren't any running tasks.\n```\n\nOriginal issue reported on code.google.com by `cebi...@gmail.com` on 5 Dec 2013 at 12:01\n\nAttachments:\n- [djangotasks.checkforrunning.patch](https://storage.googleapis.com/google-code-attachments/django-tasks/issue-21/comment-0/djangotasks.checkforrunning.patch)\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/21/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/20", "title": "Please include sample code", "body": "```\nI started the task server and added the following to my model:\n\n    def task_do_something(self):\n        self.results = process_info(self.id)\n        self.save()\n\nThen call:\ndjangotasks.register_task(MyModel.task_do_something, \"Add data returned from \nfunction\")\n\nBut in my view, I get an exception when calling:\n        task = djangotasks.task_for_object(MyModel.task_do_something)\n\nIn the log, I see no indication that the \"MyModel.task_do_something\" was \nloaded/registered.  Am I using this properly?\n\nNothing is shown in the log, just that exception in the view. It seems like the \ntask isn't registering properly.\n\n\n```\n\nOriginal issue reported on code.google.com by `jay.cros...@gmail.com` on 12 Nov 2013 at 6:01\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/20/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/19", "title": "Argument passing ?", "body": "```\n[could not find any contact information, so using the issue system]\n\nI am looking for exactly this project: a django based super minimal task \nmanager.\n\nHowever, this is one thing I am uncomfortable with: you can not pass argument \nto ask.\n\nI have for example daily and weekly tasks, that will obviously take as a date \nor a week number. How to achieve that ?\n```\n\nOriginal issue reported on code.google.com by `75.blueb...@gmail.com` on 15 Jul 2013 at 5:53\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/19/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/18", "title": "Is it plan to make it work with django python 3 version ?", "body": "```\nJust an issue to know if anyone plan to make this contribution ? One can see \nthat the projet is not updated anymore since a while. Since I will integrate it \nto a django project, I would like to know if you are interested to add me to \nthe project in order to bring my contributions in this repos otherwise I\u00a0have \nplanned to make a fork on github.\n\nThanks.\nCaner\n```\n\nOriginal issue reported on code.google.com by `ca...@candan.fr` on 29 Apr 2013 at 3:44\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/18/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/17", "title": "Scheduler tries the execute one task all the time", "body": "```\nWhat steps will reproduce the problem?\n1. Install MySQL and Django\n2. Run Djangotask\n3. Add some task to the scheduler\n\nWhat is the expected output? What do you see instead?\nThe Scheduler executed just one task.\n\nSee log:\nI added a print statement to djangotasks/models.py:282\n # ... Then start any new task\n        tasks = self.filter(status=\"scheduled\",\n                            archived=False)\n        print tasks\n        for task in tasks:\n\n\nINFO:djangotasks:Starting task 18...\nINFO:djangotasks:...Task 18 started.\nINFO:djangotasks:Task 18 finished with status \"successful\"\n[<Task: 18 - video.9.create_bittorrent>] \nWARNING:djangotasks:A task on model=videoportal.video exists in the database, \nbut is not defined in the code\nWARNING:djangotasks:A task on model=videoportal.video exists in the database, \nbut is not defined in the code\nINFO:djangotasks:Starting task 18...\nINFO:djangotasks:...Task 18 started.\nWARNING:djangotasks:Failed to change status from \"scheduled\" to \"running\" for \ntask 18\n[<Task: 18 - video.9.create_bittorrent>] \nWARNING:djangotasks:A task on model=videoportal.video exists in the database, \nbut is not defined in the code\nWARNING:djangotasks:A task on model=videoportal.video exists in the database, \nbut is not defined in the code\nINFO:djangotasks:Starting task 18...\nINFO:djangotasks:...Task 18 started.\nWARNING:djangotasks:Failed to change status from \"scheduled\" to \"running\" for \ntask 18\n[<Task: 18 - video.9.create_bittorrent>]\nWARNING:djangotasks:A task on model=videoportal.video exists in the database, \nbut is not defined in the code\nWARNING:djangotasks:A task on model=videoportal.video exists in the database, \nbut is not defined in the code\n[..every 5 sec]\n\nAs you can see the scheduler thinks the task has stil the status \"scheduled\"  \nallthough it was succesfully processed before. The scheduler gets the status \nbefore the transaction in djangotasks/models.py:288.\n\ntasks = self.filter(status=\"scheduled\",\n                            archived=False)\n\n\nWhat version of the product are you using? On what operating system?\nmysqld --version\nmysqld  Ver 5.5.28-0ubuntu0.12.04.3 for debian-linux-gnu on x86_64 ((Ubuntu))\npython --version\nPython 2.7.3\ndjango-tasks from\nhttps://github.com/Piratenfraktion-Berlin/djangotasks\n\nPlease provide any additional information below.\nThe issue is related to Mysql and Django: \nhttp://stackoverflow.com/questions/3346124/how-do-i-force-django-to-ignore-any-c\naches-and-reload-data\n\nadding the READ COMMITED Isolation to the DATABASES OPTIONS solves the issue\n\nDATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.\n        'NAME': '',                      # Or path to database file if using sqlite3.\n        'USER': '',                      # Not used with sqlite3.\n        'PASSWORD': '',                  # Not used with sqlite3.\n        'HOST': '',                      # Set to empty string for localhost. Not used with sqlite3.\n        'PORT': '',                      # Set to empty string for default. Not used with sqlite3.\n        'OPTIONS': { \"init_command\": \"SET storage_engine=INNODB, SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED\", }\n   }\n}\n\n\n\n```\n\nOriginal issue reported on code.google.com by `huhe...@googlemail.com` on 11 Jan 2013 at 2:00\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/17/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/15", "title": "Failing tests", "body": "```\nI've set up django-tasks as described on the main page. In order to get all \ntests pass I had to do the following modifications:\n\n1. Since not all time zone abbreviations are three letters long, I had to apply \nthe attached patch.\n2. I had to set the logging level to INFO in settings.py.\n3. I had to set the DJANGO_SETTINGS_MODULE and PYTHONPATH environment variables \nappropriately.\n\nIs there a way to modify the testing code so that 2. and 3. would not be \nnecessary?\n\n```\n\nOriginal issue reported on code.google.com by `akos.lad...@gmail.com` on 8 Jul 2011 at 10:10\n\nAttachments:\n- [regex.patch](https://storage.googleapis.com/google-code-attachments/django-tasks/issue-15/comment-0/regex.patch)\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/15/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/11", "title": "Feature Request - Stop Task", "body": "```\nIt's great that there's a cancel task method in django-tasks. But this is a \nvery 'ugly' solution to the \"how can I stop my long running task in the middle \nof execution\" problem. If you're unlucky your task might stop without properly \nclosing/otherwise finalizing some critical resource.\n\nI propose that the `cancel_task` method should by split into two functions:\n- stop_task(task)\n- kill_task(task)\n\n`kill_task` would function identically to how `cancel_task` currently function, \ni.e., tell the os to kill the process.\n\n`stop_task` would just set a flag on the task model, e.g., `stopped = True`. If \nthe method that is running is django-tasks aware then it would be periodically \nchecking the `stopped` flag, and upon being set to `True` it would gracefully \nexit. If the method is not django-tasks aware then this method would \neffectively do nothing.\n\n\n```\n\nOriginal issue reported on code.google.com by `topher...@gmail.com` on 28 Dec 2010 at 10:27\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/11/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/10", "title": "Better log output when running as runserver", "body": "```\nFollowing issue 9, it will be nice to format the message with the timestamp, \nlike django does.\nWe already logging the time with the log message in the log file when \ndjangotask run as a daemon.\n\nSo when using \"runserver\", instead of having:\n\n[07/Dec/2010 09:10:47] \"GET /admin/custom_media/img/favicon.ico HTTP/1.1\" 200 \n485\nTask 41 finished with status \"successful\"\nStarting task 42...\n\nwe will have:\n\n[07/Dec/2010 09:10:47] \"GET /admin/custom_media/img/favicon.ico HTTP/1.1\" 200 \n485\n[07/Dec/2010 09:10:48] Task 41 finished with status \"successful\"\n[07/Dec/2010 09:10:49] Starting task 42...\n```\n\nOriginal issue reported on code.google.com by `thomas.d...@gmail.com` on 7 Dec 2010 at 5:49\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/10/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/2", "title": "Tracebacks contain color encoding if ipython is installed", "body": "```\nI am using an early june 2010 svn export of django-tasks (probably r12) and any \ntraceback in the log output contains ANSI color escape codes if ipython is \ninstalled.\n\nUninstalling ipython resolves the issue, but its probably possible for those \ncolor tracebacks to be disabled by the code running the tasks.\n\ndjango-tasks has been working well for me so far.  Great job guys.\n```\n\nOriginal issue reported on code.google.com by `godber` on 11 Jul 2010 at 6:03\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/2/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}], "commits": [], "pull_requests": [], "issue_comments": [{"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631610", "body": "```\nI am actively using the project, for a significant piece of software.\nYour contributions are welcomed!\n```\n\nOriginal comment by `pombreda...@gmail.com` on 8 Aug 2010 at 3:32\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631610/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631612", "body": "```\nWe're indeed starting to use it in production. I'm updating the home page to \nreflect that :). \n```\n\nOriginal comment by `farial...@gmail.com` on 23 Sep 2010 at 1:49\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631612/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631614", "body": "```\nAustin, have you had any success (or problems ?) using django-tasks ? Feel free \nto open more tickets..\n```\n\nOriginal comment by `farial...@gmail.com` on 2 Dec 2010 at 11:14\n- Changed state: **Done**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631614/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631618", "body": "```\nWeird.... The log output should be pretty neutral there...\nWould you have a little more details? \n```\n\nOriginal comment by `pombreda...@gmail.com` on 8 Aug 2010 at 3:30\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631618/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631619", "body": "```\nThis issue still exists in the newer release I am using (either r14 or r15).  I \nbelieve the steps to reproduce it are to have iPython installed and then \ngenerate a traceback within your task.  You will see the ASCII color sequences \nin the log.  If you remove ipython from the running environment, then the ASCII \ncolor sequences are gone.\n\nI will try to extract this from my project and share it with you.\n\nI believe this documentation might be useful in disabling color tracebacks in \nipython, but its still not clear to me how to proceed.  I haven't really dug \ninto it yet.\nhttp://ipython.scipy.org/doc/nightly/html/api/generated/IPython.core.ultratb.htm\nl\n```\n\nOriginal comment by `godber` on 8 Aug 2010 at 10:43\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631619/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631621", "body": "```\nThis has been fixed\n```\n\nOriginal comment by `farial...@gmail.com` on 23 Sep 2010 at 1:36\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631621/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631622", "body": "```\nI'm not completely convinced. the log is supposed to be plain english, so the \ndate time should be displayed in plain english. Also, in most cases, you would \nwant to see the results in your timezone, not in UTC. However, I agree that the \noutput should include the timezone information.\n```\n\nOriginal comment by `farial...@gmail.com` on 23 Sep 2010 at 1:44\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631622/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631623", "body": "```\nTimezone information added in \nhttp://code.google.com/p/django-tasks/source/detail?r=43\n```\n\nOriginal comment by `thomas.d...@gmail.com` on 22 Jan 2011 at 1:38\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631623/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631625", "body": "```\nThanks Tom !\n```\n\nOriginal comment by `farial...@gmail.com` on 22 Jan 2011 at 7:34\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631625/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631627", "body": "```\nHi Austin,\n\nwe've added a Signal on task completion in r51\n\nYou can now connect your notification system on this Signal. \nThe Signal will give you the task (so you can get the result) and the object \ninstance as params. \nYou can now use:\n\n\nfrom djangotasks.signals import task_completed\n\ndef notification_callback(sender, **kwargs):\n    print \"Task finished!\"\n\ntask_completed.connect(notification_callback)\n\n\nSee the changes in r51 and \nhttps://docs.djangoproject.com/en/1.3/topics/signals/ for more details ;)\n```\n\nOriginal comment by `thomas.d...@gmail.com` on 27 Sep 2011 at 6:16\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631627/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631628", "body": "```\nCool, good solution, thanks!\n```\n\nOriginal comment by `godber` on 27 Sep 2011 at 6:50\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631628/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631633", "body": "```\nIt is already configurable, through the TASKS_LOG_FILE setting\n```\n\nOriginal comment by `farial...@gmail.com` on 2 Dec 2010 at 11:12\n- Changed state: **Invalid**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631633/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631636", "body": "```\nFixed in r32\n```\n\nOriginal comment by `thomas.d...@gmail.com` on 29 Nov 2010 at 7:57\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631636/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631639", "body": "Original comment by `thomas.d...@gmail.com` on 22 Jan 2011 at 1:39\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631639/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631642", "body": "```\nThomas, I believe I fixed it in revision 40. Can you check ?\n```\n\nOriginal comment by `farial...@gmail.com` on 2 Dec 2010 at 11:21\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631642/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631643", "body": "```\nBetter fix in revision 41\n```\n\nOriginal comment by `farial...@gmail.com` on 6 Dec 2010 at 7:19\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631643/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631647", "body": "```\nHello Matt.\n\nThe model has been fixed in \nhttp://code.google.com/p/django-tasks/source/detail?r=44\n\nThanks ;)\n```\n\nOriginal comment by `thomas.d...@gmail.com` on 22 Jan 2011 at 1:52\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631647/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631649", "body": "```\nyou can close this.. user mistake.. I didn't register the method correctly\n```\n\nOriginal comment by `hiji...@gmail.com` on 6 Apr 2011 at 10:34\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631649/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631651", "body": "```\nok, closing\n```\n\nOriginal comment by `farial...@gmail.com` on 19 May 2011 at 8:14\n- Changed state: **Invalid**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631651/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631653", "body": "```\nFixed in r47\n```\n\nOriginal comment by `farial...@gmail.com` on 19 May 2011 at 9:50\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631653/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631654", "body": "```\nHi,\n\nIs there any chance to include these changes to the svn version.\nAddressing 2. and 3. would also make life much easier.\n```\n\nOriginal comment by `alpar.ju...@gmail.com` on 15 Jul 2011 at 3:53\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631654/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631656", "body": "```\nHi,\n\nthe patch was applied in r48\n\nWe'll look into 2 and 3\n```\n\nOriginal comment by `thomas.d...@gmail.com` on 8 Aug 2011 at 10:28\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631656/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631659", "body": "```\nThe patch looks good, with the following caveats:\n\n * I'm not 100% happy with\n+            from django.conf import settings\n+            daemon = TaskDaemon(settings.TASKS_PID_FILE\n+                                if hasattr(settings, 'TASKS_PID_FILE')\n+                                else '/tmp/django-taskd.pid')\nthere is no need for a setting, I think: it should be a fixed place on Windows. \nIf I'm correct, the TEMP env var is always defined on Windows, so it should be \n\njoin(os.getenv('TEMP'), 'django-taskd.pid')\n\nwith a good exception behind thrown if the getenv doesn't work. Yes, I googled \na little, this is safe. So on Unix it should be always /tmp/django-taskd.pid, \nbut on Windows it should be join(os.getenv('TEMP'), 'django-taskd.pid')\n\nThen - instead of\n+                env['PYTHONPATH'] = \\\n+                    (';' if os.name == 'nt' else ':').join(sys.path)\nI would propose:\n+                env['PYTHONPATH'] = os.pathsep.join(sys.path)\n\nFinally, for\n+                                        close_fds=os.name != 'nt',\nI would rather write it\n+                                        close_fds= (os.name != 'nt'),\nfor clarity\n\n\nI would suggest we commit it, and we ping Alpar to test it ? since it wasn't \nworking (and wasn't supported :) ) before, it's always better, even if it \ndoesn't fix it yet\n\nand Alpar.ju... can be the \"official tester\" on Windows :)\n\n```\n\nOriginal comment by `farial...@gmail.com` on 13 Sep 2011 at 9:44\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631659/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631660", "body": "```\nok, patch applied in r49. Alpar, could you verify that it works for you ?\n```\n\nOriginal comment by `farial...@gmail.com` on 13 Sep 2011 at 10:05\n- Changed state: **Fixed**\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631660/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}, {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631663", "body": "```\n> there is no need for a setting, I think: it should be a fixed place on \nWindows. If > I'm correct, the TEMP env var is always defined on Windows, so it \nshould be \n\nUsing the TEMP env is a good idea. In fact, it makes me think why don't we use \n$TMPDIR on LINUX?\n\nOn the other hand, I still think that a configurable pid file may be useful, \neven on Linux. For example you may want to run two djangotasks instances with \ntwo independent django site. Currently it is impossible because both would use \nthe same pid file.\n\n> I would propose:\n> +                env['PYTHONPATH'] = os.pathsep.join(sys.path)\n\nThis is much better indeed.\n\n> Finally, for\n> +                                        close_fds=os.name != 'nt',\n> I would rather write it\n> +                                        close_fds= (os.name != 'nt'),\n> for clarity\n\nFine for me, though simply I copied my version from django 1.3 (file \nmanagement/commands/makemessages.py, line 45)\n\n> ok, patch applied in r49. Alpar, could you verify that it works for you ?\n\nYes, it works for me.\n\n> and Alpar.ju... can be the \"official tester\" on Windows :)\n\nNo way! I basically never use Windows and know nothing about it. The latest \n(and only) version that was really installed on my own computer was Windows \n3.1, way back in the early 90s.\n```\n\nOriginal comment by `alpar.ju...@gmail.com` on 14 Sep 2011 at 7:13\n", "reactions": {"url": "https://api.github.com/repos/davidkempers/django-tasks/issues/comments/82631663/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0}, "author_association": "NONE"}], "commit_comments": [], "review_comments": []}, "davidkempers": {"issues": [], "commits": [{"url": "https://api.github.com/repos/davidkempers/django-tasks/commits/7ede4d394a1052bd2f41928f044bd80b1f480333", "message": "Create README.md"}], "pull_requests": [], "issue_comments": [], "commit_comments": [], "review_comments": []}}}}